/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AMP

import com.squareup.moshi.Json

/**
 * Details relevant to AMP HTLCs, only populated if this is an AMP HTLC.
 *
 * @param rootShare 
 * @param setId 
 * @param childIndex 
 * @param hash 
 * @param preimage 
 */

data class Amp (

    @Json(name = "root_share")
    val rootShare: kotlin.String,

    @Json(name = "set_id")
    val setId: kotlin.String,

    @Json(name = "child_index")
    val childIndex: kotlin.Int,

    @Json(name = "hash")
    val hash: kotlin.String,

    @Json(name = "preimage")
    val preimage: kotlin.String

)

