/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param address Network address
 * @param port Network port
 * @param score Relative score
 */

data class BtcLocalAddress (

    /* Network address */
    @Json(name = "address")
    val address: kotlin.String,

    /* Network port */
    @Json(name = "port")
    val port: kotlin.Int,

    /* Relative score */
    @Json(name = "score")
    val score: kotlin.Int

)

