/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param isRequired 
 * @param isKnown 
 */

data class Feature (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "is_required")
    val isRequired: kotlin.Boolean? = null,

    @Json(name = "is_known")
    val isKnown: kotlin.Boolean? = null

)

