/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param chanId 
 * @param chanCapacity 
 * @param amtToForward 
 * @param fee 
 * @param expiry 
 * @param amtToForwardMsat 
 * @param feeMsat 
 * @param pubKey 
 * @param tlvPayload 
 */

data class Hop (

    @Json(name = "chan_id")
    val chanId: kotlin.Int,

    @Json(name = "chan_capacity")
    val chanCapacity: kotlin.Int,

    @Json(name = "amt_to_forward")
    val amtToForward: kotlin.Int,

    @Json(name = "fee")
    val fee: kotlin.Int,

    @Json(name = "expiry")
    val expiry: kotlin.Int,

    @Json(name = "amt_to_forward_msat")
    val amtToForwardMsat: kotlin.Int,

    @Json(name = "fee_msat")
    val feeMsat: kotlin.Int,

    @Json(name = "pub_key")
    val pubKey: kotlin.String,

    @Json(name = "tlv_payload")
    val tlvPayload: kotlin.Boolean

)

