/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChannelUpdate

import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param channelUpdate 
 * @param htlcMsat 
 * @param onionSha256 
 * @param cltvExpiry 
 * @param flags 
 * @param failureSourceIndex 
 * @param height 
 */

data class HTLCAttemptFailure (

    @Json(name = "code")
    val code: kotlin.Int,

    @Json(name = "channel_update")
    val channelUpdate: ChannelUpdate,

    @Json(name = "htlc_msat")
    val htlcMsat: kotlin.Int,

    @Json(name = "onion_sha_256")
    val onionSha256: kotlin.String,

    @Json(name = "cltv_expiry")
    val cltvExpiry: kotlin.Int,

    @Json(name = "flags")
    val flags: kotlin.Int,

    @Json(name = "failure_source_index")
    val failureSourceIndex: kotlin.Int,

    @Json(name = "height")
    val height: kotlin.Int

)

