/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.SetupApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SetupApi', function() {
    describe('getShutdownSetupShutdownGet', function() {
      it('should call getShutdownSetupShutdownGet successfully', function(done) {
        //uncomment below and update the code to test getShutdownSetupShutdownGet
        //instance.getShutdownSetupShutdownGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStatusSetupStatusGet', function() {
      it('should call getStatusSetupStatusGet successfully', function(done) {
        //uncomment below and update the code to test getStatusSetupStatusGet
        //instance.getStatusSetupStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setupFinalDoneSetupSetupFinalDonePost', function() {
      it('should call setupFinalDoneSetupSetupFinalDonePost successfully', function(done) {
        //uncomment below and update the code to test setupFinalDoneSetupSetupFinalDonePost
        //instance.setupFinalDoneSetupSetupFinalDonePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setupFinalInfoSetupSetupFinalInfoGet', function() {
      it('should call setupFinalInfoSetupSetupFinalInfoGet successfully', function(done) {
        //uncomment below and update the code to test setupFinalInfoSetupSetupFinalInfoGet
        //instance.setupFinalInfoSetupSetupFinalInfoGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setupStartDoneSetupSetupStartDonePost', function() {
      it('should call setupStartDoneSetupSetupStartDonePost successfully', function(done) {
        //uncomment below and update the code to test setupStartDoneSetupSetupStartDonePost
        //instance.setupStartDoneSetupSetupStartDonePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setupStartInfoSetupSetupStartInfoGet', function() {
      it('should call setupStartInfoSetupSetupStartInfoGet successfully', function(done) {
        //uncomment below and update the code to test setupStartInfoSetupSetupStartInfoGet
        //instance.setupStartInfoSetupSetupStartInfoGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setupSyncInfoSetupSetupSyncInfoPost', function() {
      it('should call setupSyncInfoSetupSetupSyncInfoPost successfully', function(done) {
        //uncomment below and update the code to test setupSyncInfoSetupSetupSyncInfoPost
        //instance.setupSyncInfoSetupSetupSyncInfoPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
