"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.btc_network import BtcNetwork


class TestBtcNetwork(unittest.TestCase):
    """BtcNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBtcNetwork(self):
        """Test BtcNetwork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BtcNetwork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
