"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.custom_records_entry import CustomRecordsEntry


class TestCustomRecordsEntry(unittest.TestCase):
    """CustomRecordsEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomRecordsEntry(self):
        """Test CustomRecordsEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomRecordsEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
