"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.soft_fork import SoftFork
globals()['SoftFork'] = SoftFork
from openapi_client.model.blockchain_info import BlockchainInfo


class TestBlockchainInfo(unittest.TestCase):
    """BlockchainInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockchainInfo(self):
        """Test BlockchainInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockchainInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
