"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.hop_hint import HopHint
globals()['HopHint'] = HopHint
from openapi_client.model.route_hint import RouteHint


class TestRouteHint(unittest.TestCase):
    """RouteHint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouteHint(self):
        """Test RouteHint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RouteHint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
