"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.invoice_htlc_state import InvoiceHTLCState


class TestInvoiceHTLCState(unittest.TestCase):
    """InvoiceHTLCState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoiceHTLCState(self):
        """Test InvoiceHTLCState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvoiceHTLCState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
