"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.onchain_address_type import OnchainAddressType
globals()['OnchainAddressType'] = OnchainAddressType
from openapi_client.model.new_address_input import NewAddressInput


class TestNewAddressInput(unittest.TestCase):
    """NewAddressInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewAddressInput(self):
        """Test NewAddressInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NewAddressInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
