"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.features_entry import FeaturesEntry
from openapi_client.model.invoice_htlc import InvoiceHTLC
from openapi_client.model.invoice_state import InvoiceState
from openapi_client.model.route_hint import RouteHint
globals()['FeaturesEntry'] = FeaturesEntry
globals()['InvoiceHTLC'] = InvoiceHTLC
globals()['InvoiceState'] = InvoiceState
globals()['RouteHint'] = RouteHint
from openapi_client.model.invoice import Invoice


class TestInvoice(unittest.TestCase):
    """Invoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoice(self):
        """Test Invoice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Invoice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
