"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.chain import Chain
from openapi_client.model.features_entry import FeaturesEntry
globals()['Chain'] = Chain
globals()['FeaturesEntry'] = FeaturesEntry
from openapi_client.model.ln_info import LnInfo


class TestLnInfo(unittest.TestCase):
    """LnInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLnInfo(self):
        """Test LnInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LnInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
