"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.lightning_info_lite import LightningInfoLite


class TestLightningInfoLite(unittest.TestCase):
    """LightningInfoLite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightningInfoLite(self):
        """Test LightningInfoLite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightningInfoLite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
