"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.login_input import LoginInput


class TestLoginInput(unittest.TestCase):
    """LoginInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginInput(self):
        """Test LoginInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
