"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mpp_record import MPPRecord


class TestMPPRecord(unittest.TestCase):
    """MPPRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMPPRecord(self):
        """Test MPPRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MPPRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
