/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.ChannelUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChannelUpdate', function() {
    it('should create an instance of ChannelUpdate', function() {
      // uncomment below and update the code to test ChannelUpdate
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be.a(FastApi.ChannelUpdate);
    });

    it('should have the property signature (base name: "signature")', function() {
      // uncomment below and update the code to test the property signature
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property chainHash (base name: "chain_hash")', function() {
      // uncomment below and update the code to test the property chainHash
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property chanId (base name: "chan_id")', function() {
      // uncomment below and update the code to test the property chanId
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property messageFlags (base name: "message_flags")', function() {
      // uncomment below and update the code to test the property messageFlags
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property channelFlags (base name: "channel_flags")', function() {
      // uncomment below and update the code to test the property channelFlags
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property timeLockDelta (base name: "time_lock_delta")', function() {
      // uncomment below and update the code to test the property timeLockDelta
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property htlcMinimumMsat (base name: "htlc_minimum_msat")', function() {
      // uncomment below and update the code to test the property htlcMinimumMsat
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property baseFee (base name: "base_fee")', function() {
      // uncomment below and update the code to test the property baseFee
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property feeRate (base name: "fee_rate")', function() {
      // uncomment below and update the code to test the property feeRate
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property htlcMaximumMsat (base name: "htlc_maximum_msat")', function() {
      // uncomment below and update the code to test the property htlcMaximumMsat
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

    it('should have the property extraOpaqueData (base name: "extra_opaque_data")', function() {
      // uncomment below and update the code to test the property extraOpaqueData
      //var instance = new FastApi.ChannelUpdate();
      //expect(instance).to.be();
    });

  });

}));
