/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.ConnectionInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConnectionInfo', function() {
    it('should create an instance of ConnectionInfo', function() {
      // uncomment below and update the code to test ConnectionInfo
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be.a(FastApi.ConnectionInfo);
    });

    it('should have the property lndAdminMacaroon (base name: "lnd_admin_macaroon")', function() {
      // uncomment below and update the code to test the property lndAdminMacaroon
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property lndInvoiceMacaroon (base name: "lnd_invoice_macaroon")', function() {
      // uncomment below and update the code to test the property lndInvoiceMacaroon
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property lndReadonlyMacaroon (base name: "lnd_readonly_macaroon")', function() {
      // uncomment below and update the code to test the property lndReadonlyMacaroon
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property lndTlsCert (base name: "lnd_tls_cert")', function() {
      // uncomment below and update the code to test the property lndTlsCert
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property lndRestOnion (base name: "lnd_rest_onion")', function() {
      // uncomment below and update the code to test the property lndRestOnion
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property lndBtcpayConnectionString (base name: "lnd_btcpay_connection_string")', function() {
      // uncomment below and update the code to test the property lndBtcpayConnectionString
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property lndZeusConnectionString (base name: "lnd_zeus_connection_string")', function() {
      // uncomment below and update the code to test the property lndZeusConnectionString
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property clRestZeusConnectionString (base name: "cl_rest_zeus_connection_string")', function() {
      // uncomment below and update the code to test the property clRestZeusConnectionString
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property clRestMacaroon (base name: "cl_rest_macaroon")', function() {
      // uncomment below and update the code to test the property clRestMacaroon
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

    it('should have the property clRestOnion (base name: "cl_rest_onion")', function() {
      // uncomment below and update the code to test the property clRestOnion
      //var instance = new FastApi.ConnectionInfo();
      //expect(instance).to.be();
    });

  });

}));
