/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.GenericTx();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GenericTx', function() {
    it('should create an instance of GenericTx', function() {
      // uncomment below and update the code to test GenericTx
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be.a(FastApi.GenericTx);
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property timeStamp (base name: "time_stamp")', function() {
      // uncomment below and update the code to test the property timeStamp
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property blockHeight (base name: "block_height")', function() {
      // uncomment below and update the code to test the property blockHeight
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property numConfs (base name: "num_confs")', function() {
      // uncomment below and update the code to test the property numConfs
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

    it('should have the property totalFees (base name: "total_fees")', function() {
      // uncomment below and update the code to test the property totalFees
      //var instance = new FastApi.GenericTx();
      //expect(instance).to.be();
    });

  });

}));
