/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.HTLCAttemptFailure();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HTLCAttemptFailure', function() {
    it('should create an instance of HTLCAttemptFailure', function() {
      // uncomment below and update the code to test HTLCAttemptFailure
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be.a(FastApi.HTLCAttemptFailure);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property channelUpdate (base name: "channel_update")', function() {
      // uncomment below and update the code to test the property channelUpdate
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property htlcMsat (base name: "htlc_msat")', function() {
      // uncomment below and update the code to test the property htlcMsat
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property onionSha256 (base name: "onion_sha_256")', function() {
      // uncomment below and update the code to test the property onionSha256
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property cltvExpiry (base name: "cltv_expiry")', function() {
      // uncomment below and update the code to test the property cltvExpiry
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property flags (base name: "flags")', function() {
      // uncomment below and update the code to test the property flags
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property failureSourceIndex (base name: "failure_source_index")', function() {
      // uncomment below and update the code to test the property failureSourceIndex
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new FastApi.HTLCAttemptFailure();
      //expect(instance).to.be();
    });

  });

}));
