/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.StartDoneData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StartDoneData', function() {
    it('should create an instance of StartDoneData', function() {
      // uncomment below and update the code to test StartDoneData
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be.a(FastApi.StartDoneData);
    });

    it('should have the property hostname (base name: "hostname")', function() {
      // uncomment below and update the code to test the property hostname
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

    it('should have the property forceFreshSetup (base name: "forceFreshSetup")', function() {
      // uncomment below and update the code to test the property forceFreshSetup
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

    it('should have the property keepBlockchain (base name: "keepBlockchain")', function() {
      // uncomment below and update the code to test the property keepBlockchain
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

    it('should have the property lightning (base name: "lightning")', function() {
      // uncomment below and update the code to test the property lightning
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

    it('should have the property passwordA (base name: "passwordA")', function() {
      // uncomment below and update the code to test the property passwordA
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

    it('should have the property passwordB (base name: "passwordB")', function() {
      // uncomment below and update the code to test the property passwordB
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

    it('should have the property passwordC (base name: "passwordC")', function() {
      // uncomment below and update the code to test the property passwordC
      //var instance = new FastApi.StartDoneData();
      //expect(instance).to.be();
    });

  });

}));
