/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Chain model module.
 * @module model/Chain
 * @version 1
 */
class Chain {
    /**
     * Constructs a new <code>Chain</code>.
     * @alias module:model/Chain
     * @param chain {String} 
     * @param network {String} 
     */
    constructor(chain, network) { 
        
        Chain.initialize(this, chain, network);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chain, network) { 
        obj['chain'] = chain;
        obj['network'] = network;
    }

    /**
     * Constructs a <code>Chain</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Chain} obj Optional instance to populate.
     * @return {module:model/Chain} The populated <code>Chain</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Chain();

            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} chain
 */
Chain.prototype['chain'] = undefined;

/**
 * @member {String} network
 */
Chain.prototype['network'] = undefined;






export default Chain;

