/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Feature from './Feature';

/**
 * The FeaturesEntry model module.
 * @module model/FeaturesEntry
 * @version 1
 */
class FeaturesEntry {
    /**
     * Constructs a new <code>FeaturesEntry</code>.
     * @alias module:model/FeaturesEntry
     * @param key {Number} 
     * @param value {module:model/Feature} 
     */
    constructor(key, value) { 
        
        FeaturesEntry.initialize(this, key, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, value) { 
        obj['key'] = key;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>FeaturesEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeaturesEntry} obj Optional instance to populate.
     * @return {module:model/FeaturesEntry} The populated <code>FeaturesEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeaturesEntry();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = Feature.constructFromObject(data['value']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} key
 */
FeaturesEntry.prototype['key'] = undefined;

/**
 * @member {module:model/Feature} value
 */
FeaturesEntry.prototype['value'] = undefined;






export default FeaturesEntry;

