/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeeRevenue model module.
 * @module model/FeeRevenue
 * @version 1
 */
class FeeRevenue {
    /**
     * Constructs a new <code>FeeRevenue</code>.
     * @alias module:model/FeeRevenue
     * @param day {Number} Fee revenue earned in the last 24 hours
     * @param week {Number} Fee revenue earned in the last 7days
     * @param month {Number} Fee revenue earned in the last month
     */
    constructor(day, week, month) { 
        
        FeeRevenue.initialize(this, day, week, month);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, day, week, month) { 
        obj['day'] = day;
        obj['week'] = week;
        obj['month'] = month;
    }

    /**
     * Constructs a <code>FeeRevenue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeeRevenue} obj Optional instance to populate.
     * @return {module:model/FeeRevenue} The populated <code>FeeRevenue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeeRevenue();

            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'Number');
            }
            if (data.hasOwnProperty('week')) {
                obj['week'] = ApiClient.convertToType(data['week'], 'Number');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Number');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Fee revenue earned in the last 24 hours
 * @member {Number} day
 */
FeeRevenue.prototype['day'] = undefined;

/**
 * Fee revenue earned in the last 7days
 * @member {Number} week
 */
FeeRevenue.prototype['week'] = undefined;

/**
 * Fee revenue earned in the last month
 * @member {Number} month
 */
FeeRevenue.prototype['month'] = undefined;

/**
 * Fee revenue earned in the last year. Might be null if not implemented by backend.
 * @member {Number} year
 */
FeeRevenue.prototype['year'] = undefined;

/**
 * Fee revenue earned in the last year. Might be null if not implemented by backend
 * @member {Number} total
 */
FeeRevenue.prototype['total'] = undefined;






export default FeeRevenue;

