/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelUpdate from './ChannelUpdate';

/**
 * The HTLCAttemptFailure model module.
 * @module model/HTLCAttemptFailure
 * @version 1
 */
class HTLCAttemptFailure {
    /**
     * Constructs a new <code>HTLCAttemptFailure</code>.
     * @alias module:model/HTLCAttemptFailure
     * @param code {Number} 
     * @param channelUpdate {module:model/ChannelUpdate} 
     * @param htlcMsat {Number} 
     * @param onionSha256 {String} 
     * @param cltvExpiry {Number} 
     * @param flags {Number} 
     * @param failureSourceIndex {Number} 
     * @param height {Number} 
     */
    constructor(code, channelUpdate, htlcMsat, onionSha256, cltvExpiry, flags, failureSourceIndex, height) { 
        
        HTLCAttemptFailure.initialize(this, code, channelUpdate, htlcMsat, onionSha256, cltvExpiry, flags, failureSourceIndex, height);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, channelUpdate, htlcMsat, onionSha256, cltvExpiry, flags, failureSourceIndex, height) { 
        obj['code'] = code;
        obj['channel_update'] = channelUpdate;
        obj['htlc_msat'] = htlcMsat;
        obj['onion_sha_256'] = onionSha256;
        obj['cltv_expiry'] = cltvExpiry;
        obj['flags'] = flags;
        obj['failure_source_index'] = failureSourceIndex;
        obj['height'] = height;
    }

    /**
     * Constructs a <code>HTLCAttemptFailure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HTLCAttemptFailure} obj Optional instance to populate.
     * @return {module:model/HTLCAttemptFailure} The populated <code>HTLCAttemptFailure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HTLCAttemptFailure();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('channel_update')) {
                obj['channel_update'] = ChannelUpdate.constructFromObject(data['channel_update']);
            }
            if (data.hasOwnProperty('htlc_msat')) {
                obj['htlc_msat'] = ApiClient.convertToType(data['htlc_msat'], 'Number');
            }
            if (data.hasOwnProperty('onion_sha_256')) {
                obj['onion_sha_256'] = ApiClient.convertToType(data['onion_sha_256'], 'String');
            }
            if (data.hasOwnProperty('cltv_expiry')) {
                obj['cltv_expiry'] = ApiClient.convertToType(data['cltv_expiry'], 'Number');
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = ApiClient.convertToType(data['flags'], 'Number');
            }
            if (data.hasOwnProperty('failure_source_index')) {
                obj['failure_source_index'] = ApiClient.convertToType(data['failure_source_index'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
HTLCAttemptFailure.prototype['code'] = undefined;

/**
 * @member {module:model/ChannelUpdate} channel_update
 */
HTLCAttemptFailure.prototype['channel_update'] = undefined;

/**
 * @member {Number} htlc_msat
 */
HTLCAttemptFailure.prototype['htlc_msat'] = undefined;

/**
 * @member {String} onion_sha_256
 */
HTLCAttemptFailure.prototype['onion_sha_256'] = undefined;

/**
 * @member {Number} cltv_expiry
 */
HTLCAttemptFailure.prototype['cltv_expiry'] = undefined;

/**
 * @member {Number} flags
 */
HTLCAttemptFailure.prototype['flags'] = undefined;

/**
 * @member {Number} failure_source_index
 */
HTLCAttemptFailure.prototype['failure_source_index'] = undefined;

/**
 * @member {Number} height
 */
HTLCAttemptFailure.prototype['height'] = undefined;






export default HTLCAttemptFailure;

