/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class InvoiceHTLCState.
* @enum {}
* @readonly
*/
export default class InvoiceHTLCState {
    
        /**
         * value: "accepted"
         * @const
         */
        "accepted" = "accepted";

    
        /**
         * value: "settled"
         * @const
         */
        "settled" = "settled";

    
        /**
         * value: "canceled"
         * @const
         */
        "canceled" = "canceled";

    

    /**
    * Returns a <code>InvoiceHTLCState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InvoiceHTLCState} The enum <code>InvoiceHTLCState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

