/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OnchainAddressType from './OnchainAddressType';

/**
 * The NewAddressInput model module.
 * @module model/NewAddressInput
 * @version 1
 */
class NewAddressInput {
    /**
     * Constructs a new <code>NewAddressInput</code>.
     * @alias module:model/NewAddressInput
     * @param type {module:model/OnchainAddressType}  Address-types has to be one of: * p2wkh:  Pay to witness key hash (bech32) * np2wkh: Pay to nested witness key hash     
     */
    constructor(type) { 
        
        NewAddressInput.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>NewAddressInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewAddressInput} obj Optional instance to populate.
     * @return {module:model/NewAddressInput} The populated <code>NewAddressInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewAddressInput();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], OnchainAddressType);
            }
        }
        return obj;
    }


}

/**
 *  Address-types has to be one of: * p2wkh:  Pay to witness key hash (bech32) * np2wkh: Pay to nested witness key hash     
 * @member {module:model/OnchainAddressType} type
 */
NewAddressInput.prototype['type'] = undefined;






export default NewAddressInput;

