/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OnchainAddressType.
* @enum {}
* @readonly
*/
export default class OnchainAddressType {
    
        /**
         * value: "p2wkh"
         * @const
         */
        "p2wkh" = "p2wkh";

    
        /**
         * value: "np2wkh"
         * @const
         */
        "np2wkh" = "np2wkh";

    

    /**
    * Returns a <code>OnchainAddressType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OnchainAddressType} The enum <code>OnchainAddressType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

