/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HopHint from './HopHint';

/**
 * The RouteHint model module.
 * @module model/RouteHint
 * @version 1
 */
class RouteHint {
    /**
     * Constructs a new <code>RouteHint</code>.
     * @alias module:model/RouteHint
     */
    constructor() { 
        
        RouteHint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RouteHint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RouteHint} obj Optional instance to populate.
     * @return {module:model/RouteHint} The populated <code>RouteHint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RouteHint();

            if (data.hasOwnProperty('hop_hints')) {
                obj['hop_hints'] = ApiClient.convertToType(data['hop_hints'], [HopHint]);
            }
        }
        return obj;
    }


}

/**
 * A list of hop hints that when chained together can assist in reaching a specific destination.
 * @member {Array.<module:model/HopHint>} hop_hints
 */
RouteHint.prototype['hop_hints'] = undefined;






export default RouteHint;

