/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendCoinsInput model module.
 * @module model/SendCoinsInput
 * @version 1
 */
class SendCoinsInput {
    /**
     * Constructs a new <code>SendCoinsInput</code>.
     * @alias module:model/SendCoinsInput
     * @param address {String} The base58 or bech32 encoded bitcoin address to send coins to on-chain
     * @param amount {Number} The number of bitcoin denominated in satoshis to send
     */
    constructor(address, amount) { 
        
        SendCoinsInput.initialize(this, address, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, amount) { 
        obj['address'] = address;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>SendCoinsInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendCoinsInput} obj Optional instance to populate.
     * @return {module:model/SendCoinsInput} The populated <code>SendCoinsInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendCoinsInput();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('target_conf')) {
                obj['target_conf'] = ApiClient.convertToType(data['target_conf'], 'Number');
            }
            if (data.hasOwnProperty('sat_per_vbyte')) {
                obj['sat_per_vbyte'] = ApiClient.convertToType(data['sat_per_vbyte'], 'Number');
            }
            if (data.hasOwnProperty('min_confs')) {
                obj['min_confs'] = ApiClient.convertToType(data['min_confs'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The base58 or bech32 encoded bitcoin address to send coins to on-chain
 * @member {String} address
 */
SendCoinsInput.prototype['address'] = undefined;

/**
 * The number of bitcoin denominated in satoshis to send
 * @member {Number} amount
 */
SendCoinsInput.prototype['amount'] = undefined;

/**
 * The number of blocks that the transaction *should* confirm in, will be used for fee estimation
 * @member {Number} target_conf
 */
SendCoinsInput.prototype['target_conf'] = undefined;

/**
 * A manual fee expressed in sat/vbyte that should be used when crafting the transaction (default: 0)
 * @member {Number} sat_per_vbyte
 */
SendCoinsInput.prototype['sat_per_vbyte'] = undefined;

/**
 * The minimum number of confirmations each one of your outputs used for the transaction must satisfy
 * @member {Number} min_confs
 * @default 1
 */
SendCoinsInput.prototype['min_confs'] = 1;

/**
 * A label for the transaction. Ignored by CLN backend.
 * @member {String} label
 * @default ''
 */
SendCoinsInput.prototype['label'] = '';






export default SendCoinsInput;

