/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnlockWalletInput model module.
 * @module model/UnlockWalletInput
 * @version 1
 */
class UnlockWalletInput {
    /**
     * Constructs a new <code>UnlockWalletInput</code>.
     * @alias module:model/UnlockWalletInput
     * @param password {String} The wallet password
     */
    constructor(password) { 
        
        UnlockWalletInput.initialize(this, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password) { 
        obj['password'] = password;
    }

    /**
     * Constructs a <code>UnlockWalletInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnlockWalletInput} obj Optional instance to populate.
     * @return {module:model/UnlockWalletInput} The populated <code>UnlockWalletInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnlockWalletInput();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The wallet password
 * @member {String} password
 */
UnlockWalletInput.prototype['password'] = undefined;






export default UnlockWalletInput;

