/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AMP } from './AMP';
import {
    AMPFromJSON,
    AMPFromJSONTyped,
    AMPToJSON,
} from './AMP';

/**
 * Details relevant to AMP HTLCs, only populated if this is an AMP HTLC.
 * @export
 * @interface Amp
 */
export interface Amp {
    /**
     * 
     * @type {string}
     * @memberof Amp
     */
    rootShare: string;
    /**
     * 
     * @type {string}
     * @memberof Amp
     */
    setId: string;
    /**
     * 
     * @type {number}
     * @memberof Amp
     */
    childIndex: number;
    /**
     * 
     * @type {string}
     * @memberof Amp
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof Amp
     */
    preimage: string;
}

/**
 * Check if a given object implements the Amp interface.
 */
export function instanceOfAmp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rootShare" in value;
    isInstance = isInstance && "setId" in value;
    isInstance = isInstance && "childIndex" in value;
    isInstance = isInstance && "hash" in value;
    isInstance = isInstance && "preimage" in value;

    return isInstance;
}

export function AmpFromJSON(json: any): Amp {
    return AmpFromJSONTyped(json, false);
}

export function AmpFromJSONTyped(json: any, ignoreDiscriminator: boolean): Amp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rootShare': json['root_share'],
        'setId': json['set_id'],
        'childIndex': json['child_index'],
        'hash': json['hash'],
        'preimage': json['preimage'],
    };
}

export function AmpToJSON(value?: Amp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'root_share': value.rootShare,
        'set_id': value.setId,
        'child_index': value.childIndex,
        'hash': value.hash,
        'preimage': value.preimage,
    };
}

