/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BtcLocalAddress
 */
export interface BtcLocalAddress {
    /**
     * Network address
     * @type {string}
     * @memberof BtcLocalAddress
     */
    address: string;
    /**
     * Network port
     * @type {number}
     * @memberof BtcLocalAddress
     */
    port: number;
    /**
     * Relative score
     * @type {number}
     * @memberof BtcLocalAddress
     */
    score: number;
}

/**
 * Check if a given object implements the BtcLocalAddress interface.
 */
export function instanceOfBtcLocalAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "port" in value;
    isInstance = isInstance && "score" in value;

    return isInstance;
}

export function BtcLocalAddressFromJSON(json: any): BtcLocalAddress {
    return BtcLocalAddressFromJSONTyped(json, false);
}

export function BtcLocalAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): BtcLocalAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'port': json['port'],
        'score': json['score'],
    };
}

export function BtcLocalAddressToJSON(value?: BtcLocalAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'port': value.port,
        'score': value.score,
    };
}

