/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Chain
 */
export interface Chain {
    /**
     * 
     * @type {string}
     * @memberof Chain
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof Chain
     */
    network: string;
}

/**
 * Check if a given object implements the Chain interface.
 */
export function instanceOfChain(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chain" in value;
    isInstance = isInstance && "network" in value;

    return isInstance;
}

export function ChainFromJSON(json: any): Chain {
    return ChainFromJSONTyped(json, false);
}

export function ChainFromJSONTyped(json: any, ignoreDiscriminator: boolean): Chain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'network': json['network'],
    };
}

export function ChainToJSON(value?: Chain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain': value.chain,
        'network': value.network,
    };
}

