/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HopHint
 */
export interface HopHint {
    /**
     * The public key of the node at the start of the channel.
     * @type {string}
     * @memberof HopHint
     */
    nodeId: string;
    /**
     * The unique identifier of the channel.
     * @type {string}
     * @memberof HopHint
     */
    chanId: string;
    /**
     * The base fee of the channel denominated in msat.
     * @type {number}
     * @memberof HopHint
     */
    feeBaseMsat: number;
    /**
     * The fee rate of the channel for sending one satoshi across it denominated in msat
     * @type {number}
     * @memberof HopHint
     */
    feeProportionalMillionths: number;
    /**
     * The time-lock delta of the channel.
     * @type {number}
     * @memberof HopHint
     */
    cltvExpiryDelta: number;
}

/**
 * Check if a given object implements the HopHint interface.
 */
export function instanceOfHopHint(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nodeId" in value;
    isInstance = isInstance && "chanId" in value;
    isInstance = isInstance && "feeBaseMsat" in value;
    isInstance = isInstance && "feeProportionalMillionths" in value;
    isInstance = isInstance && "cltvExpiryDelta" in value;

    return isInstance;
}

export function HopHintFromJSON(json: any): HopHint {
    return HopHintFromJSONTyped(json, false);
}

export function HopHintFromJSONTyped(json: any, ignoreDiscriminator: boolean): HopHint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nodeId': json['node_id'],
        'chanId': json['chan_id'],
        'feeBaseMsat': json['fee_base_msat'],
        'feeProportionalMillionths': json['fee_proportional_millionths'],
        'cltvExpiryDelta': json['cltv_expiry_delta'],
    };
}

export function HopHintToJSON(value?: HopHint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'node_id': value.nodeId,
        'chan_id': value.chanId,
        'fee_base_msat': value.feeBaseMsat,
        'fee_proportional_millionths': value.feeProportionalMillionths,
        'cltv_expiry_delta': value.cltvExpiryDelta,
    };
}

