/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OnchainAddressType } from './OnchainAddressType';
import {
    OnchainAddressTypeFromJSON,
    OnchainAddressTypeFromJSONTyped,
    OnchainAddressTypeToJSON,
} from './OnchainAddressType';

/**
 * 
 * @export
 * @interface NewAddressInput
 */
export interface NewAddressInput {
    /**
     * 
     * Address-types has to be one of:
     * * p2wkh:  Pay to witness key hash (bech32)
     * * np2wkh: Pay to nested witness key hash
     *     
     * @type {OnchainAddressType}
     * @memberof NewAddressInput
     */
    type: OnchainAddressType | null;
}

/**
 * Check if a given object implements the NewAddressInput interface.
 */
export function instanceOfNewAddressInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function NewAddressInputFromJSON(json: any): NewAddressInput {
    return NewAddressInputFromJSONTyped(json, false);
}

export function NewAddressInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAddressInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': OnchainAddressTypeFromJSON(json['type']),
    };
}

export function NewAddressInputToJSON(value?: NewAddressInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': OnchainAddressTypeToJSON(value.type),
    };
}

