/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const OnchainAddressType = {
    P2wkh: 'p2wkh',
    Np2wkh: 'np2wkh'
} as const;
export type OnchainAddressType = typeof OnchainAddressType[keyof typeof OnchainAddressType];


export function OnchainAddressTypeFromJSON(json: any): OnchainAddressType {
    return OnchainAddressTypeFromJSONTyped(json, false);
}

export function OnchainAddressTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnchainAddressType {
    return json as OnchainAddressType;
}

export function OnchainAddressTypeToJSON(value?: OnchainAddressType | null): any {
    return value as any;
}

