/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const TxType = {
    Unknown: 'unknown',
    Send: 'send',
    Receive: 'receive'
} as const;
export type TxType = typeof TxType[keyof typeof TxType];


export function TxTypeFromJSON(json: any): TxType {
    return TxTypeFromJSONTyped(json, false);
}

export function TxTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxType {
    return json as TxType;
}

export function TxTypeToJSON(value?: TxType | null): any {
    return value as any;
}

