/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UninstallData
 */
export interface UninstallData {
    /**
     * 
     * @type {boolean}
     * @memberof UninstallData
     */
    keepData?: boolean;
}

/**
 * Check if a given object implements the UninstallData interface.
 */
export function instanceOfUninstallData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UninstallDataFromJSON(json: any): UninstallData {
    return UninstallDataFromJSONTyped(json, false);
}

export function UninstallDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UninstallData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keepData': !exists(json, 'keepData') ? undefined : json['keepData'],
    };
}

export function UninstallDataToJSON(value?: UninstallData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keepData': value.keepData,
    };
}

