/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlockWalletInput
 */
export interface UnlockWalletInput {
    /**
     * The wallet password
     * @type {string}
     * @memberof UnlockWalletInput
     */
    password: string;
}

/**
 * Check if a given object implements the UnlockWalletInput interface.
 */
export function instanceOfUnlockWalletInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UnlockWalletInputFromJSON(json: any): UnlockWalletInput {
    return UnlockWalletInputFromJSONTyped(json, false);
}

export function UnlockWalletInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlockWalletInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function UnlockWalletInputToJSON(value?: UnlockWalletInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
    };
}

